### ISSUE TITLE
Need a PDC Battle 2

### ISSUE THREAD

**Issue by the-penwing** [impojr/PDC-Hatch-2#1]
I just sideloaded this on my versa 4 and am loving it I need a pdc battle 2

**Comment by impojr** [comment]
Thanks! I'm glad you like it! Unfortunately I won't be making a PDC Battle 2, as I don't have a Fitbit anymore.
Hope you keep enjoying the app :) !

**Comment by impojr** [comment]
Thanks! I'm glad you like it! Unfortunately I won't be making a PDC Battle 2, as I don't have a Fitbit anymore.
Hope you keep enjoying the app :) !
